# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Centered Large Asset"
  description: An asset (such as image or video) with optional supporting content
  icon: web_asset
  tags: ['video', 'image']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/component-heading!
    description: Description text to compliment the block
    asset: bookshop:structure:asset_blocks
    button: bookshop:generic/button
  styles:
    background_variant: primary

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    heading:
      _bookshop_name: generic/component-heading
      eyebrow_headline: EYEBROW HEADLINE
      primary_heading: Display a video or image
    description: >-
        Whether your business is a restaurant, a barber shop, a gym, or a café, our small business template has you covered. Add your services to the list below, as many as you like, and let people contact you or book now.
    button: bookshop:generic/button
  styles:
    background_variant: primary

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: textarea