# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Test-component"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/component-heading
  button: bookshop:generic/button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
