# Metadata about this component, to be used in the CMS
spec:
  structures:
    - card_imagery_blocks
  label: "Icon"
  description: A icon (from https://heroicons.com/) with an optional border and customisable color
  icon: bolt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  hero_icon_name: academic-cap
  icon_size: small
  icon_type: solid
  rounded_border: false
  color: "#f9f9fb"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  color:
    comment: This controls the icon color and the rounded border color (if one is included)
  icon_size:
    type: choice
    options:
      values:
        - small
        - large
  icon_type:
    type: choice
    options:
      values:
        - solid
        - outline
  
