# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Sample"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: 
  styles:
    background_variant: "Light"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: >-
      asdfsadfasdfasdfsdfsdf asdfasdf asdf
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
